---
name: Backend Coding Standard
on: [ push, pull_request_target ]
jobs:
  backend-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check status
        run: git status

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'

      - name: Add composer repositories
        env:
          USERNAME: ${{ secrets.COMPOSER_MAGENTO_USERNAME }}
          PASSWORD: ${{ secrets.COMPOSER_MAGENTO_PASSWORD }}
        run: composer config repositories.magento composer https://$USERNAME:$PASSWORD@repo.magento.com/

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run tests
        run: composer run-script test

  new-backend-lint:
    runs-on: ubuntu-latest
    name: MCS Check
    container:
      image: docker.io/davidalger/php:7.4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Check status
        run: git status

      - name: Add composer repositories
        env:
          USERNAME: ${{ secrets.COMPOSER_MAGENTO_USERNAME }}
          PASSWORD: ${{ secrets.COMPOSER_MAGENTO_PASSWORD }}
        run: composer config repositories.magento composer https://$USERNAME:$PASSWORD@repo.magento.com/

      - name: Initialize config
        id: config
        run: |
          echo "::set-output name=working-directory::${PWD/$GITHUB_WORKSPACE/}"
          echo "::set-output name=composer-cache-dir::$(composer config cache-files-dir)"

      - name: Retrieve composer cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.config.outputs.composer-cache-dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - run: composer global require hirak/prestissimo
      - run: composer install --no-interaction --dev

      - uses: mediotype/phpcs-action@v2
        with:
          enable_warnings: true # This is required for magento-coding-standards to function
          only_changed_files: false # Required to run checks on push events too
          phpcs_bin_path: vendor/bin/phpcs --standard=Magento2 --exclude=Magento2.Security.XssTemplate --ignore=vendor --extensions=php,phtml *
